[build]
  # Build command
  command = "npm install"
  
  # Directory where build artifacts are stored
  publish = "."
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect API routes to serverless functions
[[redirects]]
  from = "/api/shorturl/*"
  to = "/.netlify/functions/shorturl/:splat"
  status = 200

[[redirects]]
  from = "/api/shorturl"
  to = "/.netlify/functions/shorturl"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200