# Netlify configuration

[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

# --- Redirect rules ---
# It's best practice to list more specific rules first.

# This rule handles GET requests for redirection, like /api/shorturl/1
[[redirects]]
  from = "/api/shorturl/*"
  to = "/.netlify/functions/shorturl"
  status = 200

# This rule handles POST requests to the base endpoint /api/shorturl
[[redirects]]
  from = "/api/shorturl"
  to = "/.netlify/functions/shorturl"
  status = 200