[build]
  # Build command (not needed for serverless functions)
  command = "npm install"
  
  # Directory where build artifacts are stored
  publish = "public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API routes to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serve the main page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200